### ISSUE TITLE
docker-compose.yaml

### ISSUE THREAD

**Issue by evabronskayaa** [mibelmay/sourses#2]
Внутренние порты тоже лучше выносить в .env

```yaml
   ports:
      - "7474:7474"
      - "7687:7687"
```

**Comment by evabronskayaa** [comment]
environment

можно передавать env файл, но это так, на подумать
у тебя в целом немного переменных

**Comment by evabronskayaa** [comment]
image: neo4j:5.24.1-enterprise

не было проблем с enterprise? просто это же типа платно должно быть или там какая-то своя схема?

**Comment by mibelmay** [comment]
промучилась очень долго с enterprise, вообще поняла что у меня он только на моменте когда смотрела образы на докерхабе. я тоже подумала, что это как-то странно, у меня ничего не поднималось, но в итоге поняла что мне нужно просто добавить переменную окружения NEO4J_ACCEPT_LICENSE_AGREEMENT=yes и все заработало
