### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by evabronskayaa** [mibelmay/sourses#3]
За что отвечает директория logs? Ее тоже нет в репозитории(

**Comment by mibelmay** [comment]
это просто директория куда Neo4j складывает логи. я вообще не так видимо поняла, когда ты написала добавить папку data, я просто закинула туда данные которые я парсила, а ты имела в виду чтобы в репозитории были все файлы для поднятия docker-compose?( если да, то тогда эти csv файлики там не нужны, папка data должна быть пустая

**Comment by evabronskayaa** [comment]
Мне нужны были данные, которые заносятся в neo4j
Ты не csv заносила? или как-то может через веб-интерфейс?

**Comment by mibelmay** [comment]
я заносила csv через код, потом сделала dump базы данных и в компоузе загружаю данные в базу из этого файлика neo4j.dump
