### ISSUE TITLE
docker-compose.yaml

### ISSUE THREAD

**Issue by evabronskayaa** [mibelmay/sourses#4]
```
    command: >
      bash -c "
        if [ ! -f /var/lib/neo4j/data/neostore.db ]; then
          neo4j-admin database load ${NEO4J_DATABASE} --from-path=/var/lib/neo4j/import
        fi
        neo4j console
      "
```

давай мы лучше это вынесем в .sh файл

**Comment by evabronskayaa** [comment]
postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB_NAME}

этот коннектор конечно чет наводит страху

1. давай мы его тоже в переменные окружения может вынесем? 
2. зачем тебе постгрес?

**Comment by evabronskayaa** [comment]
Можно сделать так:
```yaml
    env_file:
      - .env
```

Чтобы все переменные постоянно не передавать в контейнеры явным образом

**Comment by mibelmay** [comment]
> 2. зачем тебе постгрес?

как я поняла, нужна бд для хранения метаданных самого airflow и на официальном сайте в docker-compose там тоже поднимали постгрес

**Comment by mibelmay** [comment]
вопрос, для каждого контейнера нужен свой файл .env?

**Comment by evabronskayaa** [comment]
> вопрос, для каждого контейнера нужен свой файл .env?

не, для всего один
